#!/bin/sh
set -e
systemd-sysusers /usr/lib/sysusers.d/creator-catcher.conf
systemd-tmpfiles --create /usr/lib/tmpfiles.d/creator-catcher.conf
if [ -d /run/systemd/system ]; then
    systemctl daemon-reload
    systemctl enable creator-catcher-web.service creator-catcher-scan.timer
    systemctl restart creator-catcher-web.service
    systemctl start creator-catcher-scan.timer
fi
